# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_geojson_to_sfc <- function(geojson, expand_geometries) {
    .Call(`_geojsonsf_rcpp_geojson_to_sfc`, geojson, expand_geometries)
}

rcpp_geojson_to_sf <- function(geojson, expand_geometries) {
    .Call(`_geojsonsf_rcpp_geojson_to_sf`, geojson, expand_geometries)
}

